In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("../data/raw/Loan_Data.csv")
df.head()

   income  credit_score  loan_amount  employment_years  loan_status
0  141958           760        43525                16            1
1   35795           846        37556                 4            1
2   20860           552        17595                11            1
3  123694           689         6969                10            1
4  148106           555        48753                14            0

In [2]:
print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())
df.info()
df.describe()
df.isnull().sum()

Dataset Shape: (1000, 5)

Columns:
['income', 'credit_score', 'loan_amount', 'employment_years', 'loan_status']
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   income            1000 non-null   int64
 1   credit_score      1000 non-null   int64
 2   loan_amount       1000 non-null   int64
 3   employment_years  1000 non-null   int64
 4   loan_status       1000 non-null   int64
dtypes: int64(5)
memory usage: 39.2 KB

income              0
credit_score        0
loan_amount         0
employment_years    0
loan_status         0
dtype: int64

In [3]:
print("Duplicate rows:", df.duplicated().sum())

print("\nUnique values:")
for column in df.columns:
    print(f"{column}: {df[column].unique()}")

print("\nMinimum values:")
print(df.min())

print("\nMaximum values:")
print(df.max())
df.describe()

Duplicate rows: 0

Unique values:
income: [141958  35795  20860 123694 148106 139879 130268  96820  74886  26265
 102386 148214  57194 107498 132727 146324  64131  80263  36023  61090
  87221  84820  20769  79735  82955  84925 141637  87969  25311 123355
 124724 103104  73707 105305  48693  91932 147723 113016 126970  45658
 104478 142537  38431  22747 143855  79150  85725 149981 104654  55773
 139346  87435  76886  86803  51551 136216  31394  89092  23890  61606
 116276 145768 100038 107313  30627  28792 128859 128557  93969  63001
  96552  43897  88148 141729 144243 140923 140174  43483 144358  68555
 145436  37159 130510 126530 100077  55920 112067  87121  89479 109475
  39457  86557  97189 129109  98953  72995  60757  29692  65758 149425
  92409  91211  85697  57065 112093 119299 149293  52606 147791  31534
 114663  60397 146678 111387  21016 109789  75591 109812  43247  44300
  94065 102798  29268 106807  32185  83704 106779  59099  28571 143372
 125512  58044  71214  81228 134752  68984  60774  22568 140151  82592
  87563  22695 144375  68190  25258 107538  59504  53159  33986  81858
 149312  32666  58660  23561  46854  84505 124488  72251  42662  28392
  50535  98603 133569  72256 109135 147478  55222  97373  99575 143684
 116354 104651  83335  30965  44538 128066  90592 118018 133252  28110
  99309  47266  72992 102948 142073 118806  26910 130989 110982 141626
 139176  20206 107054 107897 142409  43419  70636 142546 134238  70015
 137478 142096 127059  74268 130687 107939  38141 100356 125878  91910
  76044  87214 137930 139324  53827  75820  82623 101734  95450 113426
 137845  42299  63585 129225  84044  62557  69080 129556  22693 115003
 115259 132235  89163  45939  68925  62941  41834  38047  46105  95766
  35707  41976  64262 145117  43776  50080 148376  86842  81373  26776
 112787 147948  75016  29474 125830  78053  41959  25530 114856 139101
  23748 117504 118098  33545 147659  86199  54766  93530 113557  81087
 115839 136183  88840 138451  74384  71005  66576  59353  82003 103211
  72733  85318 129953 109474  43664  87172 105616 145879 113264 135386
  46736 114209 123041 132859 132181  20854 110084  58623  27392  75680
 146354  66717 139937 107092  70859 145657 124095  46309 107455  83734
  90467  72662 118506 129751 138906  32688  45342  57157  87863 126308
  72083 126081  85733 109045  54698 130078 100623  42671  45184 113384
  62107 106202 129893  71663  35708 111906  69811  22811  76250 132547
  92082 144249  54754 115742 126642  31411  22911  87270 103763  28680
 104896 103879  91295 108614 120689  31111  57504  21802  28155  93656
  59384 132561  67254  41918 105981  80713  50306  36646  66843 140975
 116601 110735 127512  36371  97371 131472  22049  51616 123727 132893
 146603  40932 137796  49855  81434  92694  63016  27400 137858  62642
  35151  71407  86690  24499  26295 140885 146071  79040  32183  49299
  32874 136336  52711  25539 127941  73351  81267 143133  68354 146063
  22557  58360 102018  22200 132476  88497  66975  41357 139121  97505
  22869 146114  81135  70108 132296 114179 110272  58467  43328 139181
 111412 106831  23987  78871  42399 148391  66214 119522 106416  90271
  64064 145615  90091 127450  60818  65525  39830  37429  26893 136381
  99909  67333  23436  94290  96213  25895  39738  50746  69377  68404
  74045 117888 149307  59790 127455  25600 114660 113179  60764  94543
  65714  76835 122946 148191 129616 125983  93744  76491 144123  38589
  63484 102989  56212  63525  67202  52635  83208  53828  38711  23420
 116752  20301  65236 135294  86235  74240 144019  85726  30492 135668
 121279  26102  70336 138015 105314 143007  46641  54584  52745 140542
  43093  86105 123746 120199  71885  56631 131217  92991  24014  31093
  38070  55777  76958 102074  30729 119713  65017  86320  47751 126400
 125864  98069 125647 125510  74748  25801  39190  69689 124290  70993
  49592  30647  28716 108891 107545 137638 109912 130627  90316 146995
  22368  97575  26655 126477  90031  96429 111083 107922  75766 144046
  33403  52097  98657 140607  30966 144862 119157 138834 113848  72921
  69726 146141  70300  42677  75609 116825  76661  51024 128211  90313
 147813  73006 115285  35338  88027 112772 133632 100135  39508 140379
  23051  68747 134692 107142 107235  74021  86412  78335  76179  52093
  89678 100738  59734  92615  93523 125103 114476 122769  37019 131721
 103613 111794 106672  93847 102750  99634  48251 123481 132566  45945
 110852  52217  28308  25949  71990  21150 109480 120235  94740 136352
  86617 114841  36896 145729  66175  27805  25237 135247  40056  65543
  76556 134548 131488  23343  33500  73222  49375  29662  36964 133429
 141692  79638  93666 105067 138937  87215  89042  33284  92789 104664
 113468  81389  29435  74340  64078  98832  71293 115981  98781  80403
  49124 115435  63919 128761 141305  55247 141172 114758 111747  82752
  76573  79101 122756  46646 124185  43049  99605 118116 117379  88385
 146131  60158  85417  43289 130226 120793  29823  80160  61975  29540
  36364  24611  47663  71991  77679 124182  50977 114704  69115 111007
 108223  80890  86387  38071  79275  92369  31938  55195 111680  24000
  90588 121042 113610 140420 123691 126306 117856  58304 131783  89449
 102986 109643  40764 128940 106027  58494  23373  32161 117532 112658
 143633 120386  47350 113008 114297  45351 108668 134585  35305  95353
  96797  85953  77458 127112  40358  23267 102745 109588  58513  46092
  31338  20412  27543 125891  53496  80692 109084 112920 143555  64425
  58756  38888  55735  67295 137474 134352 103042 105999  37955  57841
  90640  85510  54911  79031 108726  27357  52479  81476  64811  56208
  40150  91180  63286 132856  88450  41352  75069 131888 130448  34397
  61555  66959  20728  70517 139180  86234  59954  67280  99459  36779
  83932  92936  44466  56939  89896  55270  79163 102637  71934  84895
  52307  74098  80921  25486  28335 106900 146020 141954 122795 109112
 117203  31130 107508 125955 138324  80566  86703  47192  21062 104076
 109780  41545  41689  31174 108461 146174 123033  29348  43714  58102
  94460 122634 109930  26801 123150  92267  68136  43625 102873 120843
  92592  97052  64261  21542  41677  66732  70343  59081  82856 113105
 108858  39065 144097 103460 108092 146116  74693  46962  48295  33807
  62348  46432 103285 126995 111792  77854  60262  57080  21324 111267
 144707  55909 109339  39870  54578  92124 137611 123605  46790 138874
  45289  75129 113714 114246  35485  64482 106188  24748 106769  23709
 143961  50355  75771  77799  33116  45470  62344  62918  72224  59298
 128492 100219  81629  86040 119518 119835  48016  43960  53591 102848
 123333 131732 134821  87641  56395 131276 149695  42700  54620 123214
 148148  40559 113045 113396  81642  96539  41732 148675 111362  50354
  33843 130008 134065  91726  37640  72528  58413 148142  72638  72736
 127892 130133 126357  88866  39087  61430  44504  27114  98859 119657
  30975  31023  41447 110469 145899  43959  86203 139156  49703  29337
  66427 141507  81529 122023 104665 125787  51921  53307  47355 123268
 147016  24835  40159 124346  67605 141790 125616  58088]
credit_score: [760 846 552 689 555 749 309 541 550 304 418 673 364 445 523 538 476 581
 362 516 404 398 810 684 704 817 775 736 322 757 382 444 384 377 756 300
 350 745 748 787 333 647 394 371 453 549 737 417 605 567 353 535 688 700
 602 506 528 374 734 402 721 397 634 746 607 548 465 780 841 405 380 432
 437 483 629 807 368 845 352 504 425 342 410 482 819 659 580 494 392 360
 702 765 833 812 532 823 645 345 372 346 420 513 355 649 406 347 636 325
 556 307 825 773 327 515 685 664 611 306 302 662 573 805 314 491 784 338
 572 530 385 836 824 511 324 693 366 408 527 769 668 724 619 742 614 676
 588 576 802 815 436 542 842 339 847 522 305 621 767 303 803 740 493 691
 472 599 625 709 524 831 412 439 389 849 438 558 560 471 312 467 620 618
 628 718 617 633 675 758 595 648 569 590 464 678 431 341 388 701 594 442
 403 497 690 478 747 799 777 719 456 396 710 553 495 821 816 458 623 429
 591 582 310 433 601 695 517 440 509 759 655 426 677 328 761 596 706 481
 670 730 608 501 735 612 416 543 774 717 646 828 479 800 460 584 455 768
 348 383 660 447 641 626 514 331 604 728 776 585 443 723 318 317 474 801
 413 521 563 354 461 679 386 477 627 395 387 587 419 790 751 450 446 680
 381 813 822 770 525 663 579 457 358 427 414 508 820 536 658 500 577 534
 793 741 340 316 452 326 586 754 448 811 486 526 609 705 766 806 781 430
 797 407 401 574 343 796 311 638 499 788 837 315 818 671 789 451 487 470
 826 696 792 725 610 469 713 715 544 571 739 565 639 441 592 731 698 643
 361 665 319 459 656 566 622 840 631 762 694 423 337 475 753 336 615 600
 561 635 391 652 644 490 330 834 557 711 783 321 332 378 729 570 838 681
 320 752 686 462 791 507 359 498 835 505 363 637 794 843 301 415 421 727
 616 308 669 682 613 814 313 606 848 651 334 744 323 703 485 545 829 399
 597 674 365 575 583 503 666 484 726 593 683]
loan_amount: [43525 37556 17595  6969 48753 22275  9470 15225 47324 46974 47759 28196
 45287 18669 42380 43006 20577 27473 33625 20504 29089 41487  5302 36463
 49912 34259 47823 42208 35659 40840 36890 18598 24508 47287 18380 31984
 49633 13125 41059  9033 42873 22087 45901 10704 12848 26592 11924 32208
 24614  5488 44882 30923 40941 34165  6667 31213  9114 41321 12761 36116
 38768 30426 22772 43218  8712  6367 45957 46781 31200  8726 28616 32723
 42574 39958 14108 17178 40643 36324 43360 22824 13927 33144 36010 27443
 19437 49298 44778 16207 30537 40757 17040 46986 27612 33441 11471 40631
 48461 31523 36348  6177  9760 37779 26636 21353 16556 32598 16563 48790
 13234 30519 31966 21173 31987 18178 44338 29596 38174  9431 32764 26627
 44310 13906 41914 49814 18076 42650 11012 12151 33211 32117 41378 47652
 11894 18467 47641 17289 49976 48596 28171 39905 25829 39054 49139 34734
 12052  8654 28486 23743 29489 13636 11441 29611 47435 17149 39566 47368
 26675 10495 47668 18673 16130 27668 20222 28669 39068 28253 14435 33552
 42384 21393 15617 43520 14852 36401 11295 40993 39084 44575 41451 12227
 36910 41041 28384  5145 42778 21035  8040 47422 31160 22633 34344 22014
 19996 46621 16695  7852 21014 32042 38755 45390 28711 31122 14160 32213
 44420 12421 26400 38537 22727  9358 33482 37117 28164 37496 49311 34371
 43467 22625 38893 15793 36007 30766 44532 17323 12843 19210 21456 36367
 15106 42957  7472 11704  8713 10051 15756  7475  9255 19484 39503 13258
 45747 40196 45194 13533 37581 10249 24201 14686 37007  5661 49843 35137
 47828 15526  8374 30592 33982  5207 40433 28197 38400  8083 34328 47891
 25103 44891 15754 39447 20901 38004 12446 42211 34301 31116 46323 23752
 37376 21669 37916 18395 25421 31342  9895 16023 15699 14715 24169 21163
 10782 27641 23792 40585 35682 23880 43067 47685 23073 41035 42174 29837
 22826 29981 15382  9437 10435 29819 41875 36982 38328 17329 30169 26932
 39594 16421 12629 13325 33495 36750 34619 45461 13264 17686 29226 11721
 25609 12373 43675 33937 10656 13984 34984 13286 10901 36552 30709 36055
 42685 13429 19716 16138 40298 28429 10772 40732 44905 22347 21920 36822
 45108 28563 12967 16871 33763 16916 13734 38613 33179 40262 17677 23268
 17330 25733 42947 32286 11610 11430 44922 18828 47913 36497 44256 41618
 31526 35158 30032 42846 49936 34794 10448 33861 33141 14074 11406 36823
 28291 46568 37003 39406 28312 48108  6382 39171 46779  8292 38187 17411
 42285 20422 47468 37371 10693 38535 19818 36238 35874 31715 32605 39317
 36174 14956 43908 15837  8716  9481 29282 11548 42605 12758 48668 28177
 29022 45761 10542 30476 35784 27740 29817 21052 40153  5671  5163 46424
 49002  9795 15634  9798 27420 34300 29345 15749 43595 30121 42487 33411
 38361 26223 12394 19056 33380 31035 35620 24877 48404 35911 37784  8191
 38160 30000 44040  8631 11172 47080 28561 25281 33671 30364 46674 32425
 33602 28472 13080 12099 30431 36186 35111 44851 27614 31724 46991  9940
 33758 41224 12788 33082 29034 40479 16280 23052 21531 27804 33903 49857
 15142 14866  9531 43098 43278 33138 32065 34956 46732 44261 15759 10439
 47533 33270 18279 44279 49251 28888 22630 40144 36182 30538 16824 37125
 11979 31189 47600 17504 25669 11910 39964 25131 30227 10978 26991 22153
 38548 47676 44071  8983 14503 34921 21905 28953 31806 27168  9583 43714
 44896 16889 32413 17275  7461 19291 16435 32935 38453 23544 17258 35841
 15736 42643 48950 33044 44933 20997 19215 38069 28911 22030 34334 19571
 47719 33927 25714 48541 28387 33444 24921 18057 29858 49638 31062 41850
 25567 34739 48285  8754 32044  6724  6376 13706 13894 23037 23450 21406
 34725 10926 44019 14496 41068 34806 27663 46321 41495 27656 30860 21832
 43787 26727 47815 34545 49522  7520  8081 39196 41735 44213 19566 19042
 30498 16329 36656  7159 42900 24363 48241 24033 15805 40851 31832 18944
 24873 45372 28928 20379 41751 39546 29286 10110 17087 28762 22081 39947
 14596 43019 47003 23313  6013 28705  6828 12909 43356 18109  7023 19537
 31661 43659 38848 42804 32766 48590  7563 41060 34197  8586 21087 28225
 34750 11643 32523 41727 16005 48543  5161 21029 19226 33731 48922 49848
  8390 10997 17693 47092  5541 26817 42861 18428 48934 15258 21044 34411
 10469 33854 11256 15720 38937 38598  6651 24194 30051 32386 14518 21184
 38787 26621 15028 17448 39051 35447 23394 39501 35254 23509 19472  8471
 46796 35268 13329 39865 33272 47845 11397 37373 40525 29570 23284 23994
 28284 22833 30122 10017 21370 34252 12999 27436 47963  7096 30279 48363
 31201 24715 34309 20078 10105 34312  7839  8384 48619 47821 18493 22069
 12531 42051 12736 12710  6619 18975 28252 20261  6431 14067 42481 32037
 14557 42766  5162 39742 24675 13461 22015 37591 33047 39782 14833 12896
 37972 46800 35508 10347 35314  7643 45785 23681 43328 20892 22073 41768
 37262 36358 19289 12927  6171 16918 46903 44110 16929  7539 27669 10432
 25644 23745 33228 39521 36703 31928 23322 27360 34055 21376 11588 11304
 12345 29259 30470 28017 20352 38365 24446  7336 14879 37316 38340 12521
 11171 28481 23474 49629 26008  6633 17485 48617  8648 18140 22921 19357
  8137  5097 16407 35575 17722 17924  8750 32733 13535 29487 35651  9666
 21994  6727 39622 15800 42823 48039 23708 17819 14369 14283 35573 18171
 35933 10774 11519 15983 35932 35798 23133 19939  5781 32624 11823 23489
 44961 34118 39881 21280 27263 18565 25354 47951 30643 28648 46971 23658
 26253 31390 28128 18489 43314 37658 11852 34450  7551 11411 38243 26800
 15403 12239 11710 26384 26038 45846 27447  7285 42991 18521 11971 34139
 24909 16531 19721 24206 42711 11530 16116  5258  5282 18937  6898  9135
 11629 48936 24584 28551 38380 22071 25074 30188  7307 44901 16205 10906
  7591 20149 49918 44951 30150 36852 47870  6283 38691  6125  6529 31170
 13438 25095 21154 13004 14752 48360 31819 41632 31515 29217 28172 37994
 20036 16739 37220 14587 49517 35129  5645 35930 21299 35090 26953 31475
 23888 48732 14346  5587 17763 46945  9079 41116 25215 30817 29765 35112
 30556 23099 48553 11450 18230 34009 10433 38866 44864 23710 16439 46855]
employment_years: [16  4 11 10 14  2  0 19 15  1  7  6  5  8  3 13 12 17 18  9]
loan_status: [1 0]

Minimum values:
income              20206
credit_score          300
loan_amount          5097
employment_years        0
loan_status             0
dtype: int64

Maximum values:
income              149981
credit_score           849
loan_amount          49976
employment_years        19
loan_status              1
dtype: int64

,income,credit_score,loan_amount,employment_years,loan_status
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,85838.794000,565.29700,27871.183000,9.493000,0.50000
std,37817.509802,160.80247,12766.885606,5.740462,0.50025
min,20206.000000,300.00000,5097.000000,0.000000,0.00000
25%,53567.250000,424.50000,16508.000000,4.000000,0.00000
50%,86399.500000,567.00000,28632.000000,10.000000,0.50000
75%,117864.000000,698.50000,38473.500000,14.000000,1.00000
max,149981.000000,849.00000,49976.000000,19.000000,1.00000

In [4]:
print("Loan status values:")
print(df["loan_status"].value_counts())

print("\nLoan status proportions:")
print(df["loan_status"].value_counts(normalize=True))

print("\nNegative values:")
print((df < 0).sum())

print("Income <= 0:", (df["income"] <= 0).sum())
print("Credit score outside 300-850:", ((df["credit_score"] < 300) | (df["credit_score"] > 850)).sum())
print("Loan amount <= 0:", (df["loan_amount"] <= 0).sum())
print("Employment years < 0:", (df["employment_years"] < 0).sum())
print("Employment years > 50:", (df["employment_years"] > 50).sum())
df.dtypes

Loan status values:
loan_status
1    500
0    500
Name: count, dtype: int64

Loan status proportions:
loan_status
1    0.5
0    0.5
Name: proportion, dtype: float64

Negative values:
income              0
credit_score        0
loan_amount         0
employment_years    0
loan_status         0
dtype: int64
Income <= 0: 0
Credit score outside 300-850: 0
Loan amount <= 0: 0
Employment years < 0: 0
Employment years > 50: 0

income              int64
credit_score        int64
loan_amount         int64
employment_years    int64
loan_status         int64
dtype: object

In [5]:
cleaned_df = df.copy()
cleaned_df.to_csv(
    "../data/processed/cleaned_loan_data.csv",
    index=False
)
cleaned_df.shape
cleaned_df.head()

import os

print(os.path.exists("../data/processed/cleaned_loan_data.csv"))

processed_df = pd.read_csv("../data/processed/cleaned_loan_data.csv")

print(processed_df.shape)
print(processed_df.isnull().sum())

True
(1000, 5)
income              0
credit_score        0
loan_amount         0
employment_years    0
loan_status         0
dtype: int64

## Data Cleaning

The dataset contains 1,000 records and 5 features.

The following data-quality checks were performed:

- Checked for missing values.
- Checked for duplicate records.
- Checked for negative values.
- Validated the credit score range.
- Validated loan amount values.
- Validated employment years.
- Checked the target variable (`loan_status`) for valid binary values.

### Cleaning Results

- Missing values: None
- Duplicate records: None
- Negative values: None
- Invalid credit scores: None
- Invalid loan amounts: None
- Invalid employment years: None
- Target values: 0 and 1
- Target distribution: 500 records for class 0 and 500 records for class 1

Since no invalid or missing records were identified, no rows were removed or imputed during the initial cleaning stage.